# Generated by Django 4.1.1 on 2022-09-14 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatroom',
            options={'verbose_name_plural': 'ChatRooms'},
        ),
    ]
